services:
  api:
    build:
      context: ./6-1          # carpeta donde estÃ¡ tu .csproj y Dockerfile
      dockerfile: Dockerfile
    container_name: api-6-1
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"           # http://localhost:8080 -> API dentro del contenedor

  api-docker-hub:
    image: raptor57/demoapi-6-1:latest
    container_name: demoapi-6-1
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8081:8080"           # http://localhost:8081 -> API dentro del contenedor

  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "3001:3001"           # UI: http://localhost:3001
    volumes:
      - uptime-kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  uptime-kuma-data:
